from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
import time
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options= webdriver.ChromeOptions()
options.add_experimental_option("detach",True)
S=Service("E:/chromedriver_win32/chromedriver/chromedriver_win32 (5)/chromedriver.exe")
driver=webdriver.Chrome(options=options,service=S)
driver.implicitly_wait(10)
driver.maximize_window()
driver.get("https://woocommerce-850415-2933260.cloudwaysapps.com/my-account")
driver.find_element(By.NAME,"username").send_keys("test_customer")
driver.find_element(By.NAME,'password').send_keys("password")
driver.find_element(By.NAME,"login").click()
print(" Login Successfully.")
time.sleep(3)

# Product page fields test
driver.execute_script("window.open('about:blank','tab2');")
driver.switch_to.window("tab2")
driver.implicitly_wait(10)
driver.get("https://woocommerce-850415-2933260.cloudwaysapps.com/product/rf-id-card")
WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.ID,"color")))
color= Select(driver.find_element(By.ID,"color"))
color.select_by_value("Red")
S_orientation=driver.find_element(By.ID, "orientation")
driver.execute_script("arguments[0].scrollIntoView();", S_orientation)
time.sleep(1)
orientation=Select(S_orientation)
orientation.select_by_visible_text("Landscape")
time.sleep(1)
driver.find_element(By.ID, "profile_description").send_keys("Test description")
time.sleep(1)
driver.find_element(By.ID,"need_phone").click()
driver.find_element(By.ID,"phone_number").send_keys("9876543210")
AE=driver.find_element(By.CLASS_NAME, "select2-selection__rendered")
AE.click()
time.sleep(1)
driver.find_element(By.XPATH,"/html/body/span/span/span/ul/li[1]").click()
AE.click()
Border=driver.find_element(By.XPATH,"/html/body/span/span/span/ul/li[2]")
Border.click()
time.sleep(1)
driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div/div[2]/main/div[2]/div[2]/form/div/div[2]/table/tbody/tr[5]/td[2]/input").send_keys("C:\\Users\\91884\\Pictures\\Screenshots\\Pet1.png")
driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div/div[2]/main/div[2]/div[2]/form/div/div[2]/button").click()
driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div/div[1]/div/a").click()
driver.execute_script("window.scrollBy(0,400)","")
print(" Product successfully added to the Cart.")
time.sleep(3)

# Verify Required validation test
driver.execute_script("window.open('about:blank','tab3');")
driver.switch_to.window("tab3")
driver.implicitly_wait(10)
driver.get("https://woocommerce-850415-2933260.cloudwaysapps.com/product/rf-id-card")
time.sleep(1)
select_color=Select(driver.find_element(By.ID,"color"))
select_color.select_by_visible_text("Red")    
Orientation=driver.find_element(By.ID,"orientation")
Select_orientation=Select(Orientation)
driver.execute_script("arguments[0].scrollIntoView();",Orientation)
time.sleep(1)
Select_orientation.select_by_visible_text("Landscape")
Cart= driver.find_element(By.XPATH,"//button[normalize-space()='Add to cart']")
driver.execute_script("arguments[0].scrollIntoView();", Cart)
Cart.click()
time.sleep(1)
driver.get_screenshot_as_file("Add_CartError.png")
print(" Field Validation Test: 'Please fill out this field' validation is shown successfully.Please refer the screenshot for details.")
time.sleep(3)

# Check the minimum select condition for multi select field.
driver.execute_script("window.open('about:blank','tab4');")
driver.switch_to.window("tab4")
driver.get("https://woocommerce-850415-2933260.cloudwaysapps.com/product/rf-id-card")
time.sleep(2)
Sel_color= Select(driver.find_element(By.ID,"color"))
Sel_color.select_by_visible_text("Red")    
orientn= driver.find_element(By.ID,"orientation")         
Sel_orientation= Select(orientn)
driver.execute_script("arguments[0].scrollIntoView();",orientn)
time.sleep(2)
Sel_orientation.select_by_visible_text("Landscape")
driver.find_element(By.ID,"profile_description").send_keys("Test description")
driver.find_element(By.CLASS_NAME,"select2-selection__rendered").click()
Border=driver.find_element(By.XPATH,"/html/body/span/span/span/ul/li[2]")
Border.click()
Cart = driver.find_element(By.XPATH,"//button[normalize-space()='Add to cart']")
driver.execute_script("arguments[0].scrollIntoView();", Cart)
Cart.click()
driver.get_screenshot_as_file("MiniumFieldLimit_Error.png")
Error= driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div/div[1]/ul/li")
print(" 'Additional Element' field Test VALIDATION MESSAGE :: "+Error.text +" is shown ")
time.sleep(2)

#Verify product Quick view test
driver.execute_script("window.open('about:blank','tab5');")
driver.switch_to.window("tab5")
driver.get("https://woocommerce-850415-2933260.cloudwaysapps.com/shop")
driver.find_element(By.LINK_TEXT,"Quick View").click()
print(" Verify Product QuickView Test:: Successfully shows the quick View popup. But cannot find color field on popup.")
driver.quit()
